- README.md
Proposition of an official citation and addition of an _how to cite_ section.
> Addition of the citation

- README.md
- docs/source/index.rst
> Added citation in doc.

- .gitignore
- .pylintrc
- .style.yapf
- poutyne/framework/callbacks/best_model_restore.py
- poutyne/framework/callbacks/callbacks.py
- poutyne/framework/callbacks/checkpoint.py
- poutyne/framework/callbacks/clip_grad.py
- poutyne/framework/callbacks/delay.py
- poutyne/framework/callbacks/earlystopping.py
- poutyne/framework/callbacks/logger.py
- poutyne/framework/callbacks/lr_scheduler.py
- poutyne/framework/callbacks/periodic.py
- poutyne/framework/callbacks/policies.py
- poutyne/framework/callbacks/progress.py
- poutyne/framework/experiment.py
- poutyne/framework/iterators.py
- poutyne/framework/metrics.py
- poutyne/framework/model.py
- poutyne/framework/optimizers.py
- poutyne/framework/warning_manager.py
- poutyne/layers/utils.py
- poutyne/utils.py
Added [yapf](https://github.com/google/yapf) formatting to the whole repository.
The formatting is based on PEP8 with the addition of allowing lines to go up to the 120th character.
The pylint config has been updated correspondingly along with a small speedup due to multiprocessing.
> Formatting

- .travis.yml
- poutyne/utils.py
Automation and validation of the yapf linter when building with travis.
Taken from [this](https://github.com/google/yapf/blob/master/.travis.yml) .yml file from yapl repo.
> added yapf automatic lint when building

- poutyne/framework/model.py
See issue pytorch/pytorch#7844 and PR pytorch/pytorch#21613.
> Fix bug related to the change of device of the parameters and the optimizer

- poutyne/framework/callbacks/policies.py
correction of minor typos in callbacks doc.
> Doc typos correction

- setup.py
Add encoding to readme file in setup.py.
> Fix issue #40

- README.md
- docs/source/callbacks.rst
- docs/source/conf.py
- docs/source/index.rst
- poutyne/framework/callbacks/best_model_restore.py
- poutyne/framework/callbacks/callbacks.py
- poutyne/framework/callbacks/checkpoint.py
- poutyne/framework/callbacks/clip_grad.py
- poutyne/framework/callbacks/delay.py
- poutyne/framework/callbacks/earlystopping.py
- poutyne/framework/callbacks/logger.py
- poutyne/framework/callbacks/lr_scheduler.py
- poutyne/framework/callbacks/periodic.py
- poutyne/framework/callbacks/policies.py
- poutyne/framework/model.py
- poutyne/layers/utils.py
- poutyne/utils.py
Overall enhancement of the documentation by :
- Adding hyperlinks between Poutyne classes/functions.
- Adding hyperlinks to outside libraries such as Pytorch, Numpy, etc.
- Unification of documentation style.
- Correction of a few minor typos.
> Documentation enhancements

- poutyne/framework/callbacks/callbacks.py
> typo in doc

- poutyne/framework/callbacks/logger.py
- tests/framework/callbacks/test_logger.py
- Remove logging of epoch number after every epoch end
- Added on train end the logging of the last epoch number
> Tensorboard cleaner epoch logging

- poutyne/framework/callbacks/logger.py
> error in add_scalars last-epoch

- poutyne/framework/model.py
- tests/framework/model/test_multi_gpu.py
Bugfix case where model was set with multi GPU and after was set one GPU, the previously set other_device where not cleared
> Bug fix multi gpus

- README.md
- docs/source/examples/introduction.rst
- docs/source/examples/policy_interface.rst
- docs/source/examples/tips_and_tricks.rst
- docs/source/examples/train_with_policy_module.rst
- docs/source/examples/transfert_learning.rst
- docs/source/index.rst
- examples/introduction_pytorch_poutyne.ipynb
- examples/policy_cifar_example.ipynb
- examples/policy_interface.ipynb
- examples/tips_and_tricks.ipynb
- examples/transfer_learning.ipynb
- Add link to colab notebook in doc
- Add accelerator in notebooks params
- Add `pip install poutyne` in notebook
#86
> Add Google Colab

- extra_requirements.txt
- setup.py
Add extra requirements in a .txt file and in setup.py
> added extra_requirements for pip and in setup

- poutyne/framework/callbacks/progress.py
- poutyne/framework/experiment.py
- poutyne/framework/metrics/batch_metrics.py
- poutyne/framework/model.py
Also, there is no information about the `strict` flag in `load_checkpoint` and the following method used in `Model`.
> fixed some typos in doc

- docs/source/callbacks.rst
- poutyne/framework/callbacks/mlflow_logger.py
- Improved the doc readibility of MLFlow logger
- Propose a more clear separation between logger
> doc improvement for mlflow and doc improvement

- CHANGELOG.md
- poutyne/framework/experiment.py
- tests/framework/experiment/test_experiment.py
Added a method to compare the results of two experiments.
> Exp comparison

- poutyne/framework/experiment.py
Fixed verbose to false. Do we want to pass a flag for it?
> Adding best ckp reload predict

- poutyne/framework/callbacks/mlflow_logger.py
I was reading the doc and the code and found some minor typos.
> Mlflow minor doc improvement

- tests/framework/base.py
- tests/framework/callbacks/test_earlystopping.py
- tests/framework/model/base.py
- tests/framework/model/test_model.py
- Improve early stopping tests
- move capture output logic and testing method into a base case
> improved tests and moved captureio into a base case

- tests/framework/callbacks/test_color_formatting.py
I did not work on the try-catch.
> added coloring test, and do update tests

- tests/framework/callbacks/test_terminate_on_nan.py
Fail due to a todo that will change according to acceptance of PR #129
> add tests for terminate_on_nan callback

- poutyne/framework/callbacks/mlflow_logger.py
- tests/framework/callbacks/test_mlflow_logger.py
- Remove unnecessary code with the log config logic 
- Add test to increase coverage
> Fix mlflow logger

- poutyne/framework/callbacks/__init__.py
- poutyne/framework/callbacks/gradient_tracker.py
- tests/framework/callbacks/test_tracker.py
- Add an integration test for CPU and for GPU related to #71
- Improve doc quality
- Improve hint typing
> fix test, improve doc, improve hint typing

- tests/framework/callbacks/test_callback_list.py
> Improve callback list test

- poutyne/framework/callbacks/delay.py
- tests/framework/callbacks/test_delay.py
Based on doc and hint typing, a case is not possible.
Fix it and add tests for it.
> Remove dead code and add tests for CallbackList

- CHANGELOG.md
- poutyne/framework/model.py
- poutyne/utils.py
- tests/framework/model/test_model.py
> Add convert_to_numpy flag to be able to obtain tensors instead of Numpy arrays in evaluate* and predict*

- .github/workflows/docker-publish.yml
- .github/workflows/docker.yml
- Dockerfile
- README.md
- docs/source/index.rst
From PR #125. I already the deployment. If you run `docker pull ghcr.io/graal-research/poutyne:latest`, it should work.
@SauravMaheshkar Let me know what you think.
> Add Dockerfile

- poutyne/framework/callbacks/callbacks.py
- poutyne/framework/callbacks/delay.py
Use MutableSequence in isinstance check so it's possible to add multiple callbacks in DelayCallback when we use hydra
> Use Sequence in delaycallback and callbacks

- .pre-commit-config.yaml
> style: Create `.pre-commit-config.yaml`

- .github/workflows/main.yml
- .github/workflows/reusable-main.yml
- .pre-commit-config.yaml
- .pylintrc
- CHANGELOG.md
- examples/basic_random_classification_with_model_bundle.py
- examples/basic_random_regression_with_model_bundle.py
- poutyne/framework/iterators.py
- poutyne/framework/metrics/predefined/bincount.py
- poutyne/framework/model.py
- pyproject.toml
- styling_requirements.txt
- tests/framework/callbacks/test_mlflow_logger.py
- tests/framework/callbacks/test_notification.py
- tests/framework/experiment/test_checkpointing.py
- tests/framework/experiment/test_experiment.py
- tests/framework/experiment/test_is_better_than.py
- tests/framework/experiment/test_tasks.py
- tests/framework/model/test_model.py
- tests/framework/model/test_model_progress.py
- tests/test_plotting.py
Also add step to run tests in CI with only bare dependencies.
> Update Black, isort, PyLint and flake8.
